name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build release
      run: ./gradlew assembleRelease

    - name: Create GitHub Release and upload APK        
      uses: ncipollo/release-action@v1.21.0        
      with:          
        tag: ${{ github.run_number }}          
        name: Release ${{ github.run_number }}          
        artifacts: "app/build/outputs/apk/release/*.apk"          
        draft: false          
        prerelease: false
        fail_on_unmatched_files: true
